### ISSUE TITLE
NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by caseyscarborough** [cpetersen/srt#21]
I'm attempting to perform a timeshift on an SRT file using Mac OS X, but every time I do I receive the following error:

```
NoMethodError: undefined method `+' for nil:NilClass
	from /Users/Casey/.rvm/gems/ruby-1.9.3-p551/gems/srt-0.1.3/lib/srt/file.rb:167:in `block in timeshift'
	from /Users/Casey/.rvm/gems/ruby-1.9.3-p551/gems/srt-0.1.3/lib/srt/file.rb:166:in `each'
	from /Users/Casey/.rvm/gems/ruby-1.9.3-p551/gems/srt-0.1.3/lib/srt/file.rb:166:in `timeshift'
	from (irb):4
	from /Users/Casey/.rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'
```

**Comment by cpetersen** [comment]
Could you add the file you are trying to time shift and the script you are using?

**Comment by cpetersen** [comment]
Ping. I'm happy to take a look at this if you could attach the file and the script that's causing the error. Otherwise I will close this in the next few days.

**Comment by caseyscarborough** [comment]
Sorry for the late reply. For some reason I can't seem to reproduce the issue again. I believe the file I was using may have had an encoding issue (the subtitles are Japanese).

I'm currently experiencing a different issue though. Whenever I attempt to timeshift the file, the `file.timeshift` call returns `nil`, and the timeshift doesn't happen. GitHub only allows an image file, so I changed the extension and uploaded it, changing the extension back after downloading should let you get it.

[Subtitles](https://cloud.githubusercontent.com/assets/3237612/9593841/dff10d5a-5021-11e5-904b-d0b6260e2dca.jpg)

And here is the what I'm running from IRB:

```ruby
require 'srt'
file = SRT::File.parse(File.new("subtitles.srt"))
file.timeshift(:all => '-4.8s')
```

**Comment by caseyscarborough** [comment]
Actually, the object does get time shifted, but it doesn't get written to the file. Is this the expected behavior?

**Comment by cpetersen** [comment]
Yes, that's the expected behavior. Basically, you read the fine into the in memory representation using `SRT::File.parse`, then manipulate it using `timeshift`, `split`, `append` and the like. Then you write it out yourself. So in this case, it would be something like:

```ruby
require 'srt'
file = SRT::File.parse(File.new("subtitles.srt"))
file.timeshift(:all => '-4.8s')
File.open("timeshifted.srt", "w") { |out| out.write(file.to_s) }
```

I hope that helps and thank you for using srt. I'm going to close this, but feel free to reopen if it still isn't working.

**Comment by caseyscarborough** [comment]
Great! That's exactly what I was wondering. Thank you.
