### ISSUE TITLE
In some cases it generates wrong timecodes when calling #to_s

### ISSUE THREAD

**Issue by Konstantinusz** [cpetersen/srt#27]
I have a subtitle line:

`#<SRT::Line:0x000055ed8d705848 @end_time=36915.999869858395, @sequence=1156, @start_time=36915.85455630479, @text=["eg a közös hangot, akik nézeteiket tekintve a hagyomány"]>`

Calling .to_s on this subtitle line yields wrong time code:

```
1156
10:15:15,855 --> 10:15:15,000
eg a közös hangot, akik nézeteiket tekintve a hagyomány
```

**Comment by Konstantinusz** [comment]
In "gems/srt-0.1.4/lib/srt/line.rb" at line 36

```
def time_str(subframe_separator=",")
      [@start_time, @end_time].map { |t| sprintf("%02d:%02d:%02d#{subframe_separator}%s", t / 3600, (t % 3600) / 60, t % 60, sprintf("%.3f", t)[-3, 3]) }.join(" --> ")
    end
```

should be

```
def time_str(subframe_separator=",")
      [@start_time, @end_time].map { |t|  f=sprintf("%.3f", t); ip=f[0,f.size-4].to_i;fp=f[-3,3]; "%02d:%02d:%02d#{subframe_separator}%s" % [ip / 3600, (ip % 3600) / 60, ip % 60,fp] }.join(" --> ")
    end

```

**Comment by cpetersen** [comment]
Hi @Konstantinusz, thank you for the ticket and for the suggested fix! I added your code and an associated spec and pushed it to Rubygems. You should be able to pull v0.1.5.

Thanks again!
